# План:
1. Python
2. Numpy
3. Pandas
4. Regexp + regexp with dataframes
5. Texts
6. Matplotlib, Seaborn
7. Classification, clustering, binary, multiclass, multilabel
8. Metrics
9. Feature extraction
10. Pyspark/sql

<img src="gifs/start.gif" width="400">

# Python

* Целая куча упражнений на типы данных\операторы и функции

https://www.w3resource.com/python-exercises/

Типы данных:
    * Числа (7382, 3.14, 3+4j, Decimal, Fraction)
    * Строки ('net', "your's", u'радость')
    * Списки ([1, [2, 'three'], 4])
    * Словари ({'Alex': 2, 'Brian': 4})
    * Кортежи ('Leo', 21.7, 'single')
    * Множества (set(1,2,3), {'a', 'b', 'c'})
    * Файлы (open('myfile', 'r'))

1. Склеить 3 подстроки "ada", "lovelace", "was considered the world's first computer programmer.". Первые две строки сделать с большой буквы.  (★☆☆)

In [1]:
str = 'ada'.capitalize()+'lovelace'.capitalize()+"was considered the world's first computer programmer"
print(str)

AdaLovelacewas considered the world's first computer programmer


2. Удаление лишних пробельных символов справа, слева, с обоих сторон  (☆☆☆)

In [2]:
 str.replace(" ", "")

"AdaLovelacewasconsideredtheworld'sfirstcomputerprogrammer"

3. Найти первое вхождение в строку подстроки (☆☆☆)

In [3]:
s1="But if you stick with me, I’m gonna accomplish great things, Morty, and you’re gonna be part of ’em."
s2="you"

##your code
s1.find(s2)

7

* isdigit - состоит ли строка из цифр;
* isalpha - состоит ли строка из букв;
* isalnum - состоит ли строка из цифр или букв;
* islower - состоит ли строка из символов в нижнем регистре;
* isupper - состоит ли строка из символов в верхнем регистре;
* istitle - начинаются ли слова в строке с заглавной буквы.

4. Разбить строку по разделителю (☆☆☆)

In [4]:
s1="Holy#cow,#Rick!#I#didn’t#know#hanging#out#with#you#was#making#me#smarter!"

##your code
s1 = s1.split('#')
print(s1)

['Holy', 'cow,', 'Rick!', 'I', 'didn’t', 'know', 'hanging', 'out', 'with', 'you', 'was', 'making', 'me', 'smarter!']


5. Полученный массив строк склеить через пробел (★☆☆)

In [5]:
s2 = " ".join(s1)
print(s2)

Holy cow, Rick! I didn’t know hanging out with you was making me smarter!


6. Вывести данные из словаря в три строки в виде "NAME (age AGE) is a JOB" (★☆☆)

(hint: .format())

In [6]:
personal_data = {1: ("Ann", 29, "Artist"), 
               2: ("Leo", 54, "Programmer"), 
               3: ("Tiffany", 43, "Shop Assistant")}

##your code
for key, value in personal_data.items():
    print('{0} (age {1}) is a {2}'.format(value[0], value[1], value[2]))

Ann (age 29) is a Artist
Leo (age 54) is a Programmer
Tiffany (age 43) is a Shop Assistant


7. Требуется определить, является ли данный год високосным. (год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.)  (★★☆)

Входные данные: Вводится единственное число - номер года (целое, положительное, не превышает 30000).

Выходные данные: Требуется вывести слово YES, если год является високосным и NO - в противном случае.

In [7]:
year = int(input())

if (year%4 == 0 and year%100 != 0) or year%400 == 0:
    print('YES')
else:
    print('NO')

2000
YES


8. Закодируйте каждый элемент списка слов числом, результат сопоставления (слово-число) поместите в словарь.  (★☆☆)

In [8]:
words = ['Not', 'my', 'cup', 'of', 'tea']

##your code
# Из задания не совсем понятно, как именно должен выглядеть результат
d = dict()
ind = 0
for i in words:
    d[i] = ind
    ind += 1
print(d)

{'Not': 0, 'my': 1, 'cup': 2, 'of': 3, 'tea': 4}


9. Удалить второй элемент из списка по индексу\по значению  (★☆☆)

In [9]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']
dogs_copy = dogs.copy()

##your code
dogs.remove('australian cattle dog')
print(dogs)

dogs_copy.pop(1)
print(dogs)

['border collie', 'labrador retriever']
['border collie', 'labrador retriever']


10. Вывести срез списка с 3 по 5 элемент включительно и все слова перевести в верхний регистр (★☆☆)

In [10]:
dogs = ['border', 'collie', 'australian', 'cattle', 'dog', 'labrador', 'retriever']

##your code
print(list(map(lambda x: x.upper(), dogs[2:5])))

['AUSTRALIAN', 'CATTLE', 'DOG']


11. Словарь словарей. Вывести из словаря для каждого питомца его имя, породу, имя владельца, и наличие прививки. Строку вывода формировать через .format() (★☆☆)

In [11]:
pets = {'willie': {'kind': 'dog', 'owner': 'eric', 'vaccinated': True},
        'walter': {'kind': 'cockroach', 'owner': 'eric', 'vaccinated': False},
        'peso': {'kind': 'dog', 'owner': 'chloe', 'vaccinated': True},
        }

##your code
for key, value in pets.items():
    print('Имя питомца - {0}, порода - {1}, имя владельца - {2}, наличие прививки - {3}'.format(
        key, value['kind'], value['owner'], value['vaccinated']))

Имя питомца - willie, порода - dog, имя владельца - eric, наличие прививки - True
Имя питомца - walter, порода - cockroach, имя владельца - eric, наличие прививки - False
Имя питомца - peso, порода - dog, имя владельца - chloe, наличие прививки - True


12. Проверить является ли множество подмножеством другого множества  (★☆☆)

In [12]:
a=set([2, 5, 6])
b=set([2, 4, 8, 3, 5, 6])

##your code
print('Является' if a&b == a else 'Не является')

Является


13. Объединить несколько множеств (★☆☆)

In [13]:
a=set([10, 35, 6, 5])
b=set([2, 4, 8, 3, 5, 6, 35])
c=set([4, 5, 35])

##your code
d = a|b|c
print(d)

{2, 35, 3, 5, 6, 4, 8, 10}


14. Посчитать пересечение множества b с остальными из предыдущего задания  (★★☆)

(hint: set.intersection(other, ...) (или set & other &) )

In [14]:
print(b&a)
print(b&b)
print(b&c)
print(b&d)

{35, 5, 6}
{2, 3, 4, 5, 6, 35, 8}
{35, 4, 5}
{2, 3, 4, 5, 6, 35, 8}


15. Вывести множество из элементов, встречающихся в одном множестве, но не встречающиеся в обоих. (★★☆)

(hint: .symmetric_difference())

In [15]:
a=set([1, 2, 3, 4, 5])
b=set([3, 4, 5, 6, 7])

##your code
print(a^b)

{1, 2, 6, 7}


16. Предположим, есть файл с данными клиентов. В качестве простого примера воьзьмем txt-файл(нужно создать файл с предложенным/другим содержанием самостоятельно) следующего содержания:

    lastname,age,debt,occupation
    
    Adrianov,25,30000,artist
    
    Нужно считать файл data/credit_sample.txt.
    Сделать словарь вида:
        {lastname: (age,debt,occupation)}
    
    Посчитать сколько уникальных профессий получилось в словаре.
    
    Результат записать в json (★★★)

In [16]:
file = open('data/credit_sample.txt','r')

dc = dict() 
occupation = set()
firstRow = True

for row in file:
    if firstRow:
        firstRow = False
        continue 
    row = row.split(',')
    dc[row[0]] = (row[1], row[2], row[3][0:-1])
    occupation.add(row[3][0:-1])

print(dc)
print('{0} уникальных профессий'.format(len(occupation)), occupation)

{'Adrianov': ('25', '30000', 'artist'), 'Belkin': ('42', '4000', 'programmer'), 'Koltunov': ('32', '100', 'sportsman'), 'Loptev': ('25', '30000', 'artist'), 'Bobrov': ('42', '4000', 'programmer'), 'Karelin': ('32', '100', 'sportsman')}
3 уникальных профессий {'programmer', 'artist', 'sportsman'}


### os, sys, datetime

In [17]:
import os

17. Получить список файлов в папке gifs/ и оставить только файлы с расширением .gif (★★☆)

In [18]:
ls = os.listdir(path="gifs")
print(ls)

gif = list()
for obj in ls:
    if '.gif' in obj:
        gif.append(obj)
print(gif)

['cat.gif', 'dog.gif', 'Microsoft Publisher Document.pub', 'pig.gif', 'Документ Microsoft Word.docx', 'Лист Microsoft Excel.xlsx', 'Презентация Microsoft PowerPoint.pptx', 'Текстовый документ.txt', 'Точечный рисунок.bmp']
['cat.gif', 'dog.gif', 'pig.gif']


18. Создать папку с названием temp и удалить её (★☆☆)

In [19]:
os.mkdir('temp')
os.rmdir('temp')

19. Вывести переменные среды (★☆☆)

(hint: environ)

In [20]:
print(os.environ)

environ({'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\maxim\\AppData\\Roaming', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'DESKTOP-BP378FS', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'CONDA_DEFAULT_ENV': 'base', 'CONDA_EXE': 'C:\\ProgramData\\Anaconda3\\Scripts\\conda.exe', 'CONDA_PROMPT_MODIFIER': '(base) ', 'CONDA_PYTHON_EXE': 'C:\\ProgramData\\Anaconda3\\python.exe', 'CONDA_SHLVL': '1', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer', 'FPS_BROWSER_USER_PROFILE_STRING': 'Default', 'GST_PLUGIN_PATH': 'C:\\Program Files\\Prosoft-Systems\\Redkit\\gstplugins', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\Users\\maxim', 'INTELLIJ IDEA COMMUNITY EDITION': 'C:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2021.2.2\\bin;', 'KOMPAS_SDK': 'C:\\Program Fil

20. Как игнорировать warrnings?

In [21]:
import warnings
warnings.filterwarnings('ignore')

* Про datetime и timedelta 

https://www.guru99.com/date-time-and-datetime-classes-in-python.html

In [22]:
import datetime

21. Вывести сегодняшнюю, вчерашнюю и завтрашнюю дату (☆☆☆)

In [23]:
print("Вчера", datetime.datetime.today() - datetime.timedelta(days=1))
print("Сегодня", datetime.datetime.today())
print("Завтра", datetime.datetime.today() + datetime.timedelta(days=1))

Вчера 2022-10-28 22:49:06.693244
Сегодня 2022-10-29 22:49:06.693244
Завтра 2022-10-30 22:49:06.693244


22. Вывести день недели сегодняшней даты (★☆☆)

In [24]:
print("Сегодня", datetime.datetime.today().strftime("%A"))

Сегодня Saturday


23. Получить список дат за предыдущую неделю (★★☆)

In [25]:
today = datetime.date.today()
start = today - datetime.timedelta(days=today.weekday(), weeks=1)

week = list()
for i in range(7):
    week.append((start + datetime.timedelta(days=i)).strftime("%d.%m.%Y"))
print(week)

['17.10.2022', '18.10.2022', '19.10.2022', '20.10.2022', '21.10.2022', '22.10.2022', '23.10.2022']


24. Вывести дату с часами и минутами, отформатировать в формате: 01.12.2019 00:12:54 (★★☆)
            
(hint: now().strftime())

In [26]:
print(datetime.datetime.now().strftime("%d.%m.%Y %H:%M:%S"))

29.10.2022 22:49:09


25. Исходя из текущей даты вычислить дату предыдущего понедельника (★★★)

In [27]:
today = datetime.date.today()
print(today - datetime.timedelta(days=today.weekday(), weeks=1))

2022-10-17


# Numpy

### numpy в картинках (реально лучший):

https://jalammar.github.io/visual-numpy/

In [28]:
import numpy as np

1. Задать нулевой вектор размером 10 (★☆☆)

(hint: np.zeros)

In [29]:
array = np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Как найти размер занимаемой памяти любым массивом (★☆☆)

(hint: size, itemsize)

In [30]:
print("Размер массива", array.size)
print("Размер элемента", array.itemsize)
print("Размер занимаемой памяти массивом", array.size*array.itemsize)

Размер массива 10
Размер элемента 8
Размер занимаемой памяти массивом 80


3. Создать вектор из 10 нулей, кроме пятого элемента, который равен 1 (★☆☆)

In [31]:
print((np.arange(10) == 4).astype(int))

[0 0 0 0 1 0 0 0 0 0]


4. Создать вектор от 10 до 50 включительно (★☆☆)

(hint:np.arange)

In [32]:
array = np.arange(10,51)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


5. Перевернуть вектор (первый элемент будет последним) (★☆☆)

In [33]:
print(np.flip(array))

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


6. Создать матрицу 3х3 с элементами от 0 до 8 (★☆☆)

(hint: reshape)

In [34]:
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. Найти индексы не нулевых элементов в numpy array [1,2,0,0,4,0] (★☆☆)

(hint: np.nonzero)

In [35]:
array = np.array([1,2,0,0,4,0])
print(np.nonzero(array)[0])

[0 1 4]


8. Создать матрицу 10x10 array с рандомными числами и найти минимум, максимум и среднее (★☆☆)

In [36]:
matrix = np.random.random((10,10))
print('Минимум = {0}, среднее = {1}, максимум = {2}'.format(matrix.min(), matrix.max(), matrix.mean()))

Минимум = 0.0061349004644365435, среднее = 0.9990271071092391, максимум = 0.5240817504859187


9. Создать матрицу 8x8 и заполнить 0 и 1 в стиле шахматной доски (★☆☆)

(hint: array[::n])

In [37]:
matrix = np.zeros((8,8), dtype=int)
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


10. Нормализовать рандомную матрицу 5x5 (★☆☆)

(hint: (x - mean) / std)

In [38]:
matrix = np.random.random((5,5))
matrix = (matrix-matrix.mean())/matrix.std()
print(matrix.std(), matrix.mean())

0.9999999999999998 1.3322676295501878e-17


11. Найти общие элементы между двумя массивами

(hint: np.intersect1d)

In [39]:
a = np.array([7, 5, 4, 1, 2])
b = np.array([3, 2, 6, 4, 8])

print(np.intersect1d(a, b))

[2 4]


12. Извлечь целую часть рандомного массива чисел различными способами (максимум 5) (★★☆)

In [40]:
array = np.random.random(10)*100
print(np.array(list(map(lambda x: np.round(x), array))))

[33. 66. 12. 48. 24.  5. 17. 45. 94. 51.]


13. Создать рандомный вектор размера 10 и отсортировать его (★★☆)

In [41]:
print(np.sort(np.random.random(10)))

[0.02445621 0.0907676  0.11931147 0.12197473 0.49638193 0.78449733
 0.81803408 0.84097656 0.84103698 0.91299821]


14. Проверить одинаковы ли два рандомных массива А и B (★★☆)

(hint: np.allclose, np.array_equal)

In [42]:
a = np.array([7, 5, 4, 1, 2])
b = np.array([3, 2, 6, 4, 8])

print('Равны' if np.array_equal(a,b) else 'Неравны')

Неравны


15. Создать рандомный ветор размером 10 и максимальный элемент заменить на -1 (★★☆)

(hint: argmax)

In [43]:
array = np.random.random(10)
print(array)
array[np.argmax(array)] = -1
print(array)

[0.11547651 0.4497239  0.04759878 0.68018228 0.89674154 0.46388
 0.71378923 0.54246816 0.71244067 0.69231974]
[ 0.11547651  0.4497239   0.04759878  0.68018228 -1.          0.46388
  0.71378923  0.54246816  0.71244067  0.69231974]


16. Найдите самый близкий элемент к данному рандомному числу в векторе? (★★☆)

(hint: argmin)

In [44]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(Z - v)).argmin()
print(Z[index])

43.95032094683208
44


17. Посчитать среднее для каждой строки матрицы (★★☆)

In [45]:
matrix = np.random.random((5,5))
print([row.mean() for row in matrix])

[0.8107579601746494, 0.7459813438055383, 0.507691588035755, 0.5066779130838965, 0.6221972770625721]


18. Посчитать среднее со скользящим окном над массивом (★★★)

(hint: np.cumsum)

In [46]:
array = np.arange(10)
n = 3
cs = np.cumsum(array)
cs[n:] = cs[n:] - cs[:-n]
cs = cs[n - 1:]/n
print(cs)

[1. 2. 3. 4. 5. 6. 7. 8.]


<img src="gifs/bender.gif" width="400">

# Regular expressions

* Cупер статья на все времена. Особенно понятно все про такие сложные штуки как lookaround. 

https://habr.com/ru/post/349860/


* Задания на регулярки

https://regexone.com/

* На этом сайте удобно тестировать регулярку, которую мучаешь, можно написать несколько примеров и тестировать на них. Важно не забывать выбирать Python:

https://regex101.com/

1. Из строки в файле data/rejson.txt вытащить хэш. Пример:

'master_guid': '<b>233880bb4c50d247f84edc9cac9e6e29</b>_2308194320'

In [47]:
import re

file = open('data/rejson.txt','r')

for row in file:
    print(re.findall(r"\s'(\w+)_", row))

['233880bb4c50d247f84edc9cac9e6e29']
['233sd0bb4c50d247f84edc9cac9e6e20']
['ds3880bb4c50d247f84edc9cac9e6e21']
['458rg5bb4c50d247f84edc9cac9e6e22']
['233645bb4c50d247f84edc9cac9e6e23']
['hjghj33545bb4c50d247f84edc9cac94']
['23cdhhgf0bb4c50d247f84edc9cac925']
['233880bb4c50d247f84edk5n34lk5n26']
['243534b4c505kl34m534dc9cac9e6e27']
['4353gef80bb4creterg0d247f84ede28']


# Pandas

* Pandas в картинках

https://jalammar.github.io/gentle-visual-intro-to-data-analysis-python-pandas/

* 10 minutes to pandas

https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html

* 🐼реально классный твиттер чувака с крутыми pandas tricks:
    
https://mobile.twitter.com/i/moments/1158828895547854849

<img src="gifs/inprogress.gif" width="400">